### ISSUE TITLE
ENV Vars for GUI login seem to not work.

### ISSUE THREAD

**Issue by ckocyigit** [vrx-666/bind9#1]
Hello vrx-666,

the login with this docker image on my unraid server with the two environment variables you described on the readme did not work in the first place. I thought I were doing something wrong but the default credentials did work so my guess is that the env variables, which I checked within the container, seem to not affect or override the default credentials.

**Comment by vrx-666** [comment]
Yeah, thanks. I know.
Will be fixed next update.

**Comment by vrx-666** [comment]
There was only possibility set custom password, login/username was not changable.
Fixed new update is available.
You can set custom GUI_USER and GUI_PASSWORD.
I'm sorry for the lack of response, I had some problems with github notifications.
