### ISSUE TITLE
SSL support for WebUI

### ISSUE THREAD

**Issue by Leseratte10** [vrx-666/bind9#4]
Would it be possible to add SSL support for the Webmin GUI in a future update?

I tried adding it myself by mounting a volume over /etc/webmin and then enabling it at Webmin -> Webmin Configuration -> SSL Encryption -> Enable SSL, but that didn't work and in the error logs it complained about missing the "openssl" binary.

**Comment by vrx-666** [comment]
There is a new update with openssl support. I've checked self-signed certificate in Gui, but other certificates should work too.
You should bind path to certificate file (other way image update could delete certificate file)
